export const events = [
  { name: 'Tilak Ceremony', date: new Date('2024-11-21T00:00:00'), theme: 'tilak' },
  { name: "Haldi", date: new Date('2024-11-25T00:00:00'), theme: 'haldi' },
  { name: 'Mehandi Ceremony', date: new Date('2024-11-26T00:00:00'), theme: 'mehandi' },
  { name: 'Wedding', date: new Date('2024-11-27T00:00:00'), theme: 'wedding' },
  { name: 'Reception', date: new Date('2024-11-30T00:00:00'), theme: 'reception' }
] as const;

export const theme = {
  default: {
    background: 'bg-gradient-to-br from-purple-900 via-indigo-900 to-blue-900',
    text: 'text-white',
    headingText: 'text-pink-100',
    subHeadingText: 'text-indigo-200',
    accent: 'text-pink-300',
    icon: 'text-blue-300',
    cardBackground: 'bg-white bg-opacity-10',
    cardBorder: 'border-white',
    decorPrimary: 'bg-pink-500',
    decorSecondary: 'bg-blue-500',
  },
  tilak: {
    background: 'bg-gradient-to-br from-blue-800 via-blue-600 to-blue-400',
    text: 'text-white',
    headingText: 'text-yellow-100',
    subHeadingText: 'text-blue-200',
    accent: 'text-yellow-300',
    icon: 'text-blue-200',
    cardBackground: 'bg-blue-700 bg-opacity-30',
    cardBorder: 'border-blue-300',
    decorPrimary: 'bg-yellow-500',
    decorSecondary: 'bg-blue-300',
    primary: 'bg-blue-600',
    secondary: 'bg-blue-300',
  },
  haldi: {
    background: 'bg-gradient-to-br from-yellow-600 via-yellow-500 to-yellow-400',
    text: 'text-yellow-900',
    headingText: 'text-yellow-100',
    subHeadingText: 'text-yellow-200',
    accent: 'text-yellow-300',
    icon: 'text-yellow-200',
    cardBackground: 'bg-yellow-600 bg-opacity-30',
    cardBorder: 'border-yellow-300',
    decorPrimary: 'bg-yellow-300',
    decorSecondary: 'bg-yellow-500',
    primary: 'bg-yellow-500',
    secondary: 'bg-yellow-300',
  },
  mehandi: {
    background: 'bg-gradient-to-br from-green-800 via-green-600 to-green-400',
    text: 'text-white',
    headingText: 'text-green-100',
    subHeadingText: 'text-green-200',
    accent: 'text-green-300',
    icon: 'text-green-200',
    cardBackground: 'bg-green-700 bg-opacity-30',
    cardBorder: 'border-green-300',
    decorPrimary: 'bg-green-300',
    decorSecondary: 'bg-green-500',
    primary: 'bg-green-600',
    secondary: 'bg-green-300',
  },
  wedding: {
    background: 'bg-gradient-to-br from-red-200 via-red-300 to-red-400',
    text: 'text-red-900',
    headingText: 'text-red-800',
    subHeadingText: 'text-red-700',
    accent: 'text-red-600',
    icon: 'text-red-500',
    cardBackground: 'bg-red-100 bg-opacity-60',
    cardBorder: 'border-red-400',
    decorPrimary: 'bg-red-500',
    decorSecondary: 'bg-red-300',
    primary: 'bg-red-400',
    secondary: 'bg-red-200',
  },
  reception: {
    background: 'bg-gradient-to-br from-pink-100 via-pink-200 to-pink-300',
    text: 'text-pink-900',
    headingText: 'text-pink-800',
    subHeadingText: 'text-pink-700',
    accent: 'text-pink-500',
    icon: 'text-pink-600',
    cardBackground: 'bg-white bg-opacity-60',
    cardBorder: 'border-pink-300',
    decorPrimary: 'bg-pink-400',
    decorSecondary: 'bg-pink-200',
    primary: 'bg-pink-300',
    secondary: 'bg-pink-100',
  },
} as const;
